#!/usr/bin/env ruby

Vagrant.configure("2") do |config|
  config.vm.box = "gusztavvargadr/windows-10"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "windows (transmission release)"

    vb.memory = "8192"
    vb.cpus = 1
    vb.gui = false
    vb.linked_clone = true
  end

  config.vm.provision "shell", inline: <<-SHELL
    choco install visualstudio2019buildtools --package-parameters "--add Microsoft.VisualStudio.Workload.VCTools --add Microsoft.VisualStudio.Component.VC.Tools.x86.x64 --add Microsoft.VisualStudio.Component.Windows10SDK.17763 --add Microsoft.VisualStudio.Component.VC.Redist.MSM" -y --timeout=0
    choco install cmake.portable 7zip.portable ActivePerl python2 nasm git imagemagick.tool -y --timeout=0
    choco install psexec -y --ignore-checksums --timeout=0
    choco install wixtoolset --version 3.11.2 -y --timeout=0

    $paths = @(
        "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Auxiliary\\Build",
        "C:\\Perl64\\bin",
        "C:\\Python27",
        "C:\\Program Files\\NASM",
        "C:\\Program Files\\Git\\bin",
        "C:\\Program Files (x86)\\WiX Toolset v3.11\\bin" # ,
    )

    foreach ($path in $paths) {
        if (!$env:PATH.Contains($path)) {
            $env:PATH = $path + ";" + $env:PATH
        }
    }

    [Environment]::SetEnvironmentVariable("PATH", $env:PATH, [System.EnvironmentVariableTarget]::Machine)
  SHELL
end
