#!/usr/bin/env ruby

Vagrant.configure("2") do |config|
  config.vm.box = "scoreyou/baseMac"
  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.provider "virtualbox" do |vb|
    vb.name = "macos (transmission release)"

    vb.memory = "8192"
    vb.cpus = 1
    vb.gui = false
    vb.linked_clone = true
  end
end
